spring:
  application:
    name: ambulance-service
  datasource:
    url: jdbc:mysql://localhost:3306/hms_userdb
    username: root
    password: santosh@416
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8091


