version: '3.8'

services:
  service-registry:
    build:
      context: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
      - "5005:5005"   # Debug port for service-registry
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - hms-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
      - "5006:5006"   # Debug port for auth-service
    depends_on:
      - service-registry
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    networks:
      - hms-network

  api-gateway:
    build:
      context: ./hms-api-gateway
    container_name: hms-api-gateway
    ports:
      - "8082:8082"
      - "5007:5007"   # Debug port for api-gateway
    depends_on:
      - service-registry
      - auth-service
      - profile-service
      - appointment-service
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
    networks:
      - hms-network

  profile-service:
    build:
      context: ./profile-service
    container_name: profile-service
    ports:
      - "8083:8083"
      - "5008:5008"   # Debug port for profile-service
    depends_on:
      - service-registry
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
    networks:
      - hms-network

  appointment-service:
    build:
      context: ./appointent-service
    container_name: appointment-service
    ports:
      - "8084:8084"
      - "5009:5009"   # Debug port for appointment-service
    depends_on:
      - service-registry
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009
    networks:
      - hms-network

networks:
  hms-network:
    driver: bridge
