server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    prefer-ip-address: true
jwt:
  secret: myjwtsecretkey1234567890

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

